# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    filePath: 'build.sh'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      ./dist/bin/LuTest --gtest_output="xml:/dist/report/LuTest.xml"
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/dist/report'
    failTaskOnFailedTests: true
    testRunTitle: 'Lu Unit Tests'